import { useState, type ReactNode } from "react";
import { AlertDialogContext } from "./AlertDialogContext";
import { AlertDialog } from "./AlertDialog";

type AlertDialogState = {
  isOpen: boolean;
  title: string;
  message: string;
};

/**
 * This provider will provide an (AlertDialog) modal. Responsible for showing / hiding the dialog
 *
 * Parameter (Props or Properties): children (a type of ReactNode), which is just the <App /> component.
 *
 */
export function AlertDialogProvider({ children }: { children: ReactNode }) {
  // Generated by ChatGPT
  // https://www.youtube.com/watch?v=n7xQVRpYHYY
  const [dialog, setDialog] = useState<AlertDialogState | null>(null);

  /**
   * Show the Alert Dialog
   * @param title title of the dialog
   * @param message the content
   */
  function showAlert(title: string, message: string) {
    // this will trigger a re-render
    setDialog({ isOpen: true, title, message });
  }

  function handleClose() {
    setDialog(null);
    // this is just setDialog ( {title: unchanged, message: unchanged, isOpen: false} )
  }

  return (
    <AlertDialogContext.Provider value={{ showAlert }}>
      {children}{" "}
      {/* Entire app. children is <App /> Component. Check "/src/main.tsx" */}
      {/* Render the Dialog */}
      {dialog && (
        <>
          {/* very elegant */}
          {/* pass the title, message and handleClose function via props (Properties)*/}
          <AlertDialog
            title={dialog.title}
            message={dialog.message}
            handleClose={handleClose}
          />
        </>
      )}
    </AlertDialogContext.Provider>
  );
}
