import LoginCard from "../../components/Auth/AuthCard/LoginCard";
import logo from "../../assets/workoutPal.png";
import "./AuthPage.css";

export default function LoginPage() {
  return (
    <div className="auth-card-holder">
      <div className="login-content">
        <div className="workoutpal-logo">
          {/* Logo generated by Google Gemini. Further modified using GIMP */}
          <img className="workoutpal-img" src={logo} alt="" />
          <h1 className="workoutpal-title">WorkoutPal</h1>
          <p className="workoutpal-motto">Get better, together</p>
        </div>
        <LoginCard />
      </div>
    </div>
  );
}
