import { useState, type ReactNode } from "react";
import { AlertDialogContext } from "./AlertDialogContext";
import "./Dialog.css";

type AlertDialogState = {
  isOpen: boolean;
  title: string;
  message: string;
};

/**
 * Shows/Hides a dialog in the current page.
 * 
 * ----
 * 
 * Parameter (Props or Properties): children (a type of ReactNode), which is just the <App /> component.
 * 
 */
export function AlertDialogProvider({ children }: { children: ReactNode }) {
  // Generated by ChatGPT
  // https://www.youtube.com/watch?v=n7xQVRpYHYY
  const [dialog, setDialog] = useState<AlertDialogState>({
    isOpen: false,
    title: "",
    message: "",
  });

  /**
   * Usage: showAlert(title, message)
   * @param title title of the dialog
   * @param message the content
   */
  function showAlert(title: string, message: string) {
    // this will trigger a re-render
    setDialog({ isOpen: true, title, message });
  }

  function handleClose() {
    setDialog((prev) => ({ ...prev, isOpen: false }));
  }

  return (
    <AlertDialogContext.Provider value={{ showAlert }}>
      {children} {/* Entire app. children is <App /> Component. Check "/src/main.tsx" */}

      {/* Dialog */}
      {dialog.isOpen && (
        <div className="dialog-backdrop" >
          <div className="dialog-container" >
            <h3>{dialog.title}</h3>
            <p>{dialog.message}</p>
            <div className="actions">
              <button onClick={handleClose}>OK</button>
            </div>
          </div>
        </div>
      )}
    </AlertDialogContext.Provider>
  );
}
