import './WeeklyGrid.css';
import { useWorkouts } from '../../hooks/useWorkouts.ts';
import { getTodayIndex, daysShortForm } from '../../utils/date.ts';

export default function WeeklyGrid() {

  const { workoutNames, exerciseNames } = useWorkouts();

  return (
    <>
      <table className="weekly-grid-table">
        <thead className="weekly-grid-table-header">
          {/* While printing out the days, highlight today's day*/}
          {
            daysShortForm.map((day, index) => (
              <th className={(index == getTodayIndex() ? "highlight-text" : "")}>{day}</th>
            ))
          }
        
        
          {/* List of workout names per day*/}
          <tr>
          {
            workoutNames.map((names) => (
              <th>{names}</th>
            ))
          }
          </tr>
        </thead>

        {/* Code for mapping each array of exercises into a column is generated by ChatGPT*/}
        <tbody>
            
            {Array.from({ length: 6 }).map((_, rowIndex) => (
            <tr key={rowIndex}>
              
              {exerciseNames.map((colArray, colIndex) => (
                <td key={colIndex} className="weekly-grid-table-list">
                  {colArray[rowIndex] === undefined ? "-" : `${rowIndex+1}.`} {colArray[rowIndex]}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </>
  );
};
