import type { Achievement } from "../../types/api";

// sample achievements for display, do not send this to the backend
export const mockAchievements: Achievement[] = [
    {
        id: 1,
        title: "Welcome, Pal!",
        description: "Log in for the first time.",
        badgeIcon: "😄",
        earnedAt: "2025-10-01",
        userId: 123,
    },
    {
        id: 2,
        title: "Knowledge Sharing",
        description: "Share a workout routine",
        badgeIcon: "💡",
        earnedAt: "",
        userId: 123,
    },
    {
        id: 3,
        title: "Uplift a WorkoutPal",
        description: "Spread positivity by liking a friend’s workout post",
        badgeIcon: "🚀",
        earnedAt: "",
        userId: 123,
    },
    {
        id: 4,
        title: "Social Butterfly",
        description: "Connect with 5 friends.",
        badgeIcon: "🦋",
        earnedAt: "",
        userId: 123,
    },
    {
        id: 5,
        title: "Consistency is Key",
        description: "Complete a workout routine 5 days in a row",
        badgeIcon: "📶",
        earnedAt: "",
        userId: 123,
    },
    {
        id: 6,
        title: "Start of my Journey",
        description: "Create your first workout routine",
        badgeIcon: "🌄",
        earnedAt: "2025-10-01",
        userId: 123,
    },
    {
        id: 7,
        title: "Gym Extrovert",
        description: "Gain 100 Followers",
        badgeIcon: "💯",
        earnedAt: "",
        userId: 123,
    },
    {
        id: 9,
        title: "AChievement",
        description: "AChievement",
        badgeIcon: "🏋️",
        earnedAt: "",
        userId: 123,
    },
    {
        id: 10,
        title: "AChievement",
        description: "AChievement",
        badgeIcon: "🏋️",
        earnedAt: "",
        userId: 123,
    },
    {
        id: 11,
        title: "AChievement",
        description: "AChievement",
        badgeIcon: "🏋️",
        earnedAt: "",
        userId: 123,
    },
    {
        id: 12,
        title: "AChievement",
        description: "AChievement",
        badgeIcon: "🏋️",
        earnedAt: "",
        userId: 123,
    },
];