import '../../styles/templates/weekly-grid.css';

export default function WeeklyGrid() {

  // Temporary hard coded data
  const routine = ['Mon', 'Tues', 'Wed', 'Thurs', 'Fri', 'Sat', 'Sun'];
  const names = ['Push', 'Rest', 'Pull', 'Rest', 'Legs', 'Rest', 'Rest'];
  const exercises = [["Workout 1", "Workout 2", "Workout 3"],[], ["Workout 1", "Workout 2", "Workout 3"], [], ["Workout 1", "Workout 2", "Workout 3"], [], []];
  const maxRows = Math.max(...exercises.map((col) => col.length));

  function getTodayIndex() {
    const today = new Date();
    console.log(today.getDay());
    return today.getDay()-1; // -1 to offset for base 0
  }

  return (
    <>
      <table className="weekly-grid-table">
        <thead className="weekly-grid-table-header">
          {
            routine.map((day, index) => (
              <th className={index == getTodayIndex() ? "highlight-text" : ""}>{day}</th>
            ))
          }
        
        <tr>
        {/* List of exercise names per day*/}
        {
          names.map((names) => (
            <th>{names}</th>
          ))
        }
        </tr>
        </thead>

        <tbody>
            {/* Code for mapping each array of exercises into a column is generated by ChatGPT*/}
            {Array.from({ length: maxRows }).map((_, rowIndex) => (
            <tr key={rowIndex}>
              {exercises.map((colArray, colIndex) => (
                <td key={colIndex}>
                  {colArray[rowIndex] ?? "-"} {/* if no exercise, print a dash */}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </>
  );
};
